# Generated by Django 5.0.6 on 2024-06-17 16:57

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_city_created_at_user_created_at_onetimepassword_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetimepassword',
            name='is_active',
        ),
        migrations.AddField(
            model_name='onetimepassword',
            name='finish_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
