# Generated by Django 5.0.6 on 2024-06-17 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_remove_onetimepassword_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='profiles_id',
            field=models.ManyToManyField(blank=True, related_name='profiles', to='app.profile'),
        ),
    ]
