# Generated by Django 5.0.6 on 2024-06-17 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_favourite_profiles_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='favourite',
            name='owner_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
